imitation_planner:
  _target_: src.planners.imitation_planner.ImitationPlanner
  _convert_: "all"

  replan_interval: 1

  planner:
    _target_: src.models.planTF.planning_model.PlanningModel
    _convert_: "all"

    dim: 128
    state_channel: 6
    polygon_channel: 6
    history_channel: 9
    history_steps: 21
    future_steps: 80
    encoder_depth: 4
    drop_path: 0.2
    num_heads: 8
    num_modes: 6
    state_dropout: 0.75
    use_ego_history: false
    state_attn_encoder: true

    feature_builder:
      _target_: src.feature_builders.nuplan_feature_builder.NuplanFeatureBuilder
      _convert_: "all"
      radius: 100
      history_horizon: 2
      future_horizon: 8
      sample_interval: 0.1
      max_agents: 32

  planner_ckpt:
